title: Pramod Naik's Portfolio
email: pramodkumta26@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the portfolio site of Pramod Naik, an aspiring software developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pramodkumta26
github_username: Pramod26naik

# Build settings
theme: minima
plugins:
  - jekyll-feed
